logging:
  file:
    path: D:\log\yuke
spring:
  datasource:
    url: jdbc:mysql://47.99.86.144:3306/wish
    username: root
    password: 123abcqwe
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 120.55.183.2
      port: 6379