server:
  port: 8081
  address: 0.0.0.0


logging:
  file:
    path: D:\log\yuke
spring:
  datasource:
    url: jdbc:mysql://192.168.253.226/wish
    username: root
    password: yukemysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 120.55.183.2
      port: 6379