server:
  port: 8081
  address: 127.0.0.1

logging:
  file:
    path: /var/log/yuke

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wish
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    data:
      redis:
        host: 127.0.0.1
        port: 6379

file-picture:
  URL: http://192.168.50.35:8081
  address:
    path: /home/jsuer/log/yuke/
    headshot: headshot
    signature:
      student: signature/student
      wish: signature/wish
      team: signature/team
      teacher: signature/teacher