server:
    port: 8081
    address: 0.0.0.0


spring:
    profiles:
        active: dev
    application:
        name: volunteer-filling
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    main:
        allow-circular-references: true
    datasource:
        url: jdbc:mysql://47.99.86.144:3306/wish
        username: root
        password: 123abcqwe
        driver-class-name: com.mysql.cj.jdbc.Driver
    data:
        redis:
            host: ${redis.host:120.55.183.2}
            port: ${redis.port:6379} #redis通信地址
            timeout: 1000 #超时时间ms
            password: 021028qwe
            lettuce:
                pool: #连接池
                    minIdle: 30
                    maxIdle: 500
                    maxWait: 10000
                    maxActive: 500
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true #开启驼峰转下划线
    mapper-locations: classpath:com/social/demo/dao/mapper/*.xml

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
    oss:
        file:
            endpoint: oss-cn-beijing.aliyuncs.com
            keyid: LTAI5tBq6BzcnToWG84snx4S
            keysecret: Nfj2tDXI5nBjtAYHNttywa7hK3fHVb
            bucketname: social-application
    #bucket可以在控制台创建，也可以使用java代码创建

#JWT 双token
jwt:
    tokenHeader: Authorization
    expire:
        accessToken: 7200 #（秒）30分钟:1800秒 2小时:7200秒 2天:172800秒 7天:604800秒
        refreshToken: 172800 #（秒）2天
    secret: abcdefghabcdefghabcdefghabcdefgh

security:
    releasable-path: #可放行资源
        - /user/login #登录
        - /user/refresh/* #刷新token
        - /user/loginVerify/image #登录验证码
        - /user/loginVerify/base64 #图片Base54
        - /user/register #注册
        - /user/register/send/** #注册手机验证码发送
file:
    URL: http://192.168.50.35:8081
logging:
    level:
        root: INFO # 日志级别，可选值为：TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
#        org.springframework: OFF
#        com.baomidou.mybatisplus: OFF


    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 控制台日志输出格式
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 日志文件输出格式
    logback:
        rolling policy:
            max-history: 30
            total-size-cap: 1GB
            max-file-size: 10MB

file-test:
    url: http://192.168.50.35:8081
    address:
        headshot: headshot
        signature:
            student: signature/student
            wish: signature/wish
            team: signature/team
            teacher: signature/teacher