version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social
      MYSQL_USER: test
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
#    networks:
#        - backend
